version: "3.9"

services:

  alembic_migrations:
    container_name: alembic-migrations
    image: alembic-migrations
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - env/.env
    command: sh -c " pwd && ls -a &&
      ./scripts/run_migrations.sh
      "
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data/