version: 1
disable_existing_loggers: false


formatters:
  json:
    "()": "pythonjsonlogger.jsonlogger.JsonFormatter"
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"

  file_format:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json

  file_app:
    class: logging.FileHandler
    level: DEBUG
    formatter: file_format
    filename: logs/app.log


loggers:
  app:
    handlers:
      - console
      - file_app
    level: DEBUG
    propagate: false

  uvicorn.access:
    handlers:
      - console
    level: INFO
    propagate: false

  uvicorn.error:
    handlers:
      - console
    level: INFO
    propagate: false

  sqlalchemy:
    handlers:
      - console
    level: INFO
    propagate: false
