version: 1
disable_existing_loggers: false


formatters:
  json:
    "()": "pythonjsonlogger.jsonlogger.JsonFormatter"
    format: "%(asctime)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s"

  my_stdout:
    format: "%(asctime)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s"

  docker:
    format: "%(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s"


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: docker

loggers:
  app:
    handlers:
      - console
    level: DEBUG
    propagate: false

  uvicorn.access:
    handlers:
      - console
    level: ERROR
    propagate: false

  uvicorn.error:
    handlers:
      - console
    level: ERROR
    propagate: false

  sqlalchemy:
    handlers:
      - console
    level: ERROR
    propagate: false

  sqlalchemy.engine.Engine:
    handlers:
      - console
    level: ERROR
    propagate: false