"""init2

Revision ID: 0af078b6e90b
Revises: c3d65fccc749
Create Date: 2025-04-09 23:06:19.399393

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0af078b6e90b"
down_revision: str | None = "c3d65fccc749"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
