"""init4

Revision ID: 6627d80cc226
Revises: 0af078b6e90b
Create Date: 2025-04-09 23:18:03.464029

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6627d80cc226"
down_revision: str | None = "0af078b6e90b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
