"""new_field_and_index

Revision ID: 2caab16c2002
Revises: 685b0f325434
Create Date: 2025-04-23 20:58:07.255748

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2caab16c2002"
down_revision: str | None = "685b0f325434"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    op.drop_column("users", "deactivated_at")
    # ### end Alembic commands ###
